### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by stefanos82** [restoreddev/phpapprentice#28]
Great work @restoreddev .

Can you provide a TODO list so people can recommend things that could or should be added to the book?

You have mentioned Closures, but I haven't seen anywhere anything about `use ()`.

What about the latest 7.x features, like `declare(strict_types=1)` or things like magic methods?

Oh you got me excited right now, this looks fantastic! ^_^

**Comment by asiby** [comment]
Just send a pull request he will merge it. That's what Open Source is about.

**Comment by restoreddev** [comment]
I had been thinking about making a general roadmap. I will leave the issue open and add it here for discussion when it's ready.

**Comment by stefanos82** [comment]
Very nice. It would be nice if you had a `SUGGESTIONS.md` file that includes user suggestions and their nicknames; you know, for reciprocating credibility.

That's how you do a healthy type of "business" so to speak.

**Comment by restoreddev** [comment]
I have added a roadmap section to the README. I think it is best to just go ahead and close this issue and if someone wants to request another topic or give feedback, they can open a new issue. Thanks for the positive feedback!
