### ISSUE TITLE
ePub version

### ISSUE THREAD

**Issue by Xe** [restoreddev/phpapprentice#29]
It would be nice to have an [ePub](https://www.lifewire.com/create-epub-file-from-html-and-xml-3467282) version of this book as a reference. Can you look into doing this please?

**Comment by asiby** [comment]
I am sure that if you give it a shot and send a pull request he will merge it. Other could step in and help you too. Just set the wheel in motion.

**Comment by restoreddev** [comment]
While making an ePub version would be great, I would like to focus on the fleshing out the content first and then distributing to other formats. Thanks for the feedback! It's good to know there is interest in an offline copy.
