### ISSUE TITLE
Add install instructions for Linux

### ISSUE THREAD

**Issue by ankush981** [restoreddev/phpapprentice#37]
Current we have installation instructions for Windows and MacOS. Please consider adding them for Linux as well. A good thing to do might even be to copy some existing content with proper credits.

**Comment by restoreddev** [comment]
I am welcome to merge in Linux instructions if someone wants to write them, however, there are so many distributions of Linux, the instructions can get out of hand. I also can safely assume that most people who are using Linux for development can figure out how to install PHP on their own.
