### ISSUE TITLE
Variable Names

### ISSUE THREAD

**Issue by davidofug** [restoreddev/phpapprentice#39]
Hey,
This is a great initiative.
I'm a bit concerned when it comes to the style of variable names? Especially when the name of the variable exceeds a single word.
Don't you think, consistence is required? Instead of having different styles? Say either CamelCase or  camelCase or variable_name or variablename?

Thank you.

**Comment by restoreddev** [comment]
Generally, I use camel case like `$redBalloon`. There are a few cases where I don't follow that convention to be descriptive. That would be something good to add to the contribution instructions though. Thanks!
